# Generated by Django 2.2.12 on 2022-01-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0002_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='intack',
            field=models.IntegerField(max_length=2),
        ),
    ]
