# Generated by Django 2.2.12 on 2022-01-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affairs', '0004_auto_20220126_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='intack',
            new_name='intake',
        ),
    ]
